spring:
  profiles:
    active: test
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/boottest
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    mongodb:
      uri: mongodb://test:boot@localhost:27017/testboot

  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false

mybatis:
  type-aliases-package: com.example.entity
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml